In [1]:
import numpy as np

In [8]:
arr = np.array([1, 3, 6])

array([1, 3, 6])

In [2]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [4]:
# numpy.zeros(shape, dtype=float, order='C', *, like=None)
np.zeros(shape=(10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# numpy.ones(shape, dtype=None, order='C', *, like=None)
np.ones(shape=(10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.random.seed(101)
# random.randint(low, high=None, size=None, dtype=int)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [10]:
arr.max()

95

In [11]:
# numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)
# Returns the indices of the maximum values along an axis.
arr.argmax()

0

In [12]:
arr.argmin()

7

In [13]:
arr.mean()

60.8

In [15]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [27]:
# np.linspace(10.0, 10.0, num=25).reshape((5,5))

np.full(shape=(5,5), fill_value=10.0)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])